build:
	go build ./x/bcapp/
	go build -o bcapp ./cmd/bc-appd/main.go
	# go build -o bc-app-cli ./cmd/bc-appcli/main.go
	@echo "\nBuild success."
	@echo "\n Use ./bcapp [command]"

install:
	# go install ./cmd/tttd
	# go install ./cmd/tttcli